In [1]:
import torch
import numpy as np

In [4]:
np_data = np.arange(6).reshape((2,3))
torch_data = torch.from_numpy(np_data)

In [7]:
print(np_data)
print(torch_data)
print(torch_data.numpy())

[[0 1 2]
 [3 4 5]]
tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)
[[0 1 2]
 [3 4 5]]


In [10]:
data = np.array([[1,2],[3,4]])
tensor = torch.FloatTensor(data)
print(np.matmul(data, data))
print(torch.mm(tensor, tensor))

[[ 7 10]
 [15 22]]
tensor([[ 7., 10.],
        [15., 22.]])
