In [1]:
import torch
from torch.autograd import Variable

In [2]:
t = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(t, requires_grad=True)

In [3]:
print(t, "\n",variable)

tensor([[1., 2.],
        [3., 4.]]) 
 tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [4]:
t_out = torch.mean(t**2)
v_out = torch.mean(variable**2)
print(t_out, "\n", v_out)

tensor(7.5000) 
 tensor(7.5000, grad_fn=<MeanBackward0>)


In [5]:
v_out.backward()
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [13]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]
